CREATE TABLE topicos (
  id BIGINT NOT NULL AUTO_INCREMENT,
  idUsuario VARCHAR(20) NOT NULL UNIQUE,
  mensaje VARCHAR(200) NOT NULL,
  nombreCurso VARCHAR(100) NOT NULL,
  titulo VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);
