CREATE TABLE topicos (
  id BIGINT NOT NULL AUTO_INCREMENT,
  id_usuario VARCHAR(20) NOT NULL,
  mensaje VARCHAR(200) NOT NULL,
  nombre_curso VARCHAR(200) NOT NULL,
  titulo VARCHAR(200) NOT NULL,
  PRIMARY KEY (id)
);
